apiVersion: v1
kind: PersistentVolume
metadata:
 name: kafka
spec:
 storageClassName: kafka-pv
 persistentVolumeReclaimPolicy: Retain
 accessModes:
  - ReadWriteMany 
 capacity:
  storage: 5Gi
 hostPath:
   path: /mnt/kafka
   type: DirectoryOrCreate
  
