apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rbac
  namespace: de
subjects:
  - kind: ServiceAccount
    name: airflow-user
    namespace: de
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io