apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: postgres
  namespace: database
spec:
   resources:
      requests:
        storage: 10Gi
   accessModes:
       - ReadWriteMany
   storageClassName: postgres-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: registry
  namespace: registry
spec:
   resources:
      requests:
        storage: 10Gi
   accessModes:
       - ReadWriteMany
   storageClassName: registry-pv