apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-pod
  namespace: cdc
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:latest
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
              subPath: zk/data
            - name: zookeeper-data
              mountPath: /datalog
              subPath: zk/datalog
      volumes: 
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: cdc
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 29000
      targetPort: 2181
  type: LoadBalancer

