kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow 
  namespace: de 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app : airflow 
  template: 
    metadata: 
      labels: 
        app: airflow 
    spec: 
      initContainers:
        - name: airflow-db-init
          image: apache/airflow:2.2.4
          imagePullPolicy: IfNotPresent
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql://airflow:admin123@postgres-service.database.svc.cluster.local:5435/airflow_metadatabase
          command:
            - airflow
          args:
            - db
            - init
      containers: 
        - name: airflow-scheduler 
          image: 'apache/airflow:2.2.4' 
          imagePullPolicy: IfNotPresent 
          env: 
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
              value: postgresql://airflow:admin123@postgres-service.database.svc.cluster.local:5435/airflow_metadatabase
            - name: AIRFLOW__CORE__EXECUTOR 
              value: KubernetesExecutor
          volumeMounts: 
            - name: airflow
              mountPath: /opt/airflow/logs 
              subPath: logs
            - name: airflow
              mountPath: /opt/airflow/dags 
              subPath: dags
            - name: airflow
              mountPath: /opt/airflow/config 
              subPath: config
            - name: airflow
              mountPath: /opt/airflow/plugins 
              subPath: plugins
          command: 
            - scheduler 
          resources: 
            requests: 
              cpu: 400m 
              memory: 512Mi
            limits: 
              cpu: 1
              memory: 1.5Gi
        - name: airflow-webserver 
          image: 'apache/airflow:2.2.4'
          env: 
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN 
              value: postgresql://airflow:admin123@postgres-service.database.svc.cluster.local:5435/airflow_metadatabase
            - name: AIRFLOW__CORE__EXECUTOR 
              value: KubernetesExecutor
          imagePullPolicy: IfNotPresent 
          ports: 
            - containerPort: 8080 
          command: 
            - webserver 
          resources: 
            requests: 
              cpu: 400m 
              memory: 512Mi
            limits: 
              cpu: 1
              memory: 1.5Gi
      restartPolicy: Always 
      volumes: 
        - name: airflow 
          persistentVolumeClaim: 
            claimName: airflow
---
kind: Service 
apiVersion: v1 
metadata: 
  name: airflow 
  namespace: de 
spec: 
  selector:
    app: airflow
  type: LoadBalancer 
  ports: 
    - name: http
      protocol: TCP 
      port: 4100
      targetPort: 8080