apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  storageClassName: minio-sc
  persistentVolumeReclaimPolicy: Retain
  capacity:
   storage: 5Gi
  accessModes: 
   - ReadWriteMany
  hostPath:
   path: /mnt/minio
   type: DirectoryOrCreate
