apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: de
  name: airflow-role
rules:
  - apiGroups: [""]
    resources: ["Pods"]
    verbs: ["get","watch","list","create","delete","update","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get","watch","list","create","delete","update","patch"]
  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","watch","list","create","delete","update","patch"]

