apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: de
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: 10.64.140.0:10000/etl/sparkbase:v1
          imagePullPolicy: Always
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master-service:7077"]
          ports:
            - containerPort: 8081
