apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: de
spec:
  serviceName: "spark-master-service"
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: 10.64.140.0:10000/etl/sparkbase:v1
          imagePullPolicy: Always
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.master.Master","--host", "spark-master-0.spark-master-service.de.svc.cluster.local", "--port", "7077"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: de
spec:
  selector:
    app: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: web-ui
      port: 8080
      targetPort: 8080
  type: LoadBalancer
