kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: airflow-k8s-pod
  namespace: de 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app : airflow-k8s 
  template: 
    metadata: 
      labels: 
        app: airflow-k8s 
    spec: 
      initContainers:
        - name: airflow-db-init
          image: '10.64.140.0:10000/etl/airflow:v1'
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: airflow-k8s-config
          command:
            - airflow
          args:
            - db
            - init
      containers: 
        - name: airflow-scheduler 
          image: '10.64.140.0:10000/etl/airflow:v1'
          imagePullPolicy: Always 
          envFrom:
            - configMapRef:
                name: airflow-k8s-config
          volumeMounts: 
            - name: airflow
              mountPath: /opt/airflow/logs 
              subPath: logs
            - name: airflow
              mountPath: /opt/airflow/dags 
              subPath: dags
            - name: airflow
              mountPath: /opt/airflow/config 
              subPath: config
            - name: airflow
              mountPath: /opt/airflow/plugins 
              subPath: plugins
          command: 
            - airflow 
          args: 
            - scheduler 
          resources: 
            requests: 
              cpu: 400m 
              memory: 200Mi
            limits: 
              cpu: 1
              memory: 1.5Gi
        - name: airflow-webserver 
          image: '10.64.140.0:10000/etl/airflow:v1'
          envFrom:
            - configMapRef:
                name: airflow-k8s-config
          imagePullPolicy: Always 
          ports: 
            - containerPort: 8080 
          command: 
            - airflow 
          args: 
            - webserver 
          volumeMounts: 
            - name: airflow
              mountPath: /opt/airflow/logs 
              subPath: logs
            - name: airflow
              mountPath: /opt/airflow/dags 
              subPath: dags
            - name: airflow
              mountPath: /opt/airflow/config 
              subPath: config
            - name: airflow
              mountPath: /opt/airflow/plugins 
              subPath: plugins
          resources: 
            requests: 
              cpu: 400m 
              memory: 512Mi
            limits: 
              cpu: 1
              memory: 2Gi
      restartPolicy: Always 
      volumes: 
        - name: airflow 
          persistentVolumeClaim: 
            claimName: airflow
---
kind: Service 
apiVersion: v1 
metadata: 
  name: airflow-k8s-service 
  namespace: de 
spec: 
  selector:
    app: airflow-k8s
  type: LoadBalancer 
  ports: 
    - name: http
      protocol: TCP 
      port: 27000
      targetPort: 8080
