apiVersion: apps/v1
kind: Deployment
metadata: 
    name: keycloak-pod
    namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.1
          ports:
            - containerPort: 8080
          env :
              - name: KEYCLOAK_ADMIN
                value: "admin"
              - name: KEYCLOAK_ADMIN_PASSWORD
                value: "admin"
              # - name: KC_HTTPS_CERTIFICATE_FILE
              #   value: "/etc/certs/tls.crt"
              # - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              #   value: "/etc/certs/tls.key"
              - name: KC_HEALTH_ENABLED
                value: "true"
              - name: KC_METRICS_ENABLED
                value: "true"
              # - name: KC_HOSTNAME
              #   value: localhost1
              # - name: KC_PROXY
              #   value: "edge"
              - name: KC_DB
                value: postgres
              - name: KC_DB_URL
                value: "jdbc:postgresql://192.168.232.148:5432/keycloak"
              - name: KC_DB_USERNAME
                value: "postgres"
              - name: KC_DB_PASSWORD
                value: "020@kcalb"
              # - name: jgroups.dns.query
              #   value: keycloak
          args: ["start-dev"]
          resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: keycloak-service
    namespace: auth
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer


