apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: mysql
  namespace: database
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: mysql-pv
