apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pod
  namespace: devops
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.22.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /etc/prometheus
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 400m
              memory: 2Gi
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus
           
---
apiVersion: v1
kind: Service 
metadata:
  name: prometheus-service
  namespace: devops
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      name: http
      port: 3200
      targetPort: 9090
  type: LoadBalancer