apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-pod
  namespace: database
spec: 
  serviceName: "mysql-service"
  replicas: 1
  selector:  
   matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
          volumeMounts:
            - name: data-dir
              mountPath: /var/lib/mysql
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: mysql
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  namespace: database
spec: 
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 3306
  type: LoadBalancer