apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: postgres
  namespace: database
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: postgres-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: registry
  namespace: registry
spec:
   resources:
      requests:
        storage: 50Mi
   accessModes:
       - ReadWriteMany
   storageClassName: registry-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: mysql
  namespace: database
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: mysql-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: sonarqube
  namespace: devops
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: sonarqube-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: prometheus
  namespace: devops
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: prometheus-pv
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: airflow
  namespace: de
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: airflow-pv