apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: postgres
  namespace: database
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: postgres-pv
