apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: registry
  namespace: registry
spec:
   resources:
      requests:
        storage: 50Mi
   accessModes:
       - ReadWriteMany
   storageClassName: registry-pv
