apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: sonarqube
  namespace: devops
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: sonarqube-pv
