apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: airflow
  namespace: de
spec:
   resources:
      requests:
        storage: 5Gi
   accessModes:
       - ReadWriteMany
   storageClassName: airflow-pv