apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  namespace: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: rediscache
          image: redis:latest
          #image: http://192.168.0.105:2000/redis:v2
          ports:
            - containerPort: 6379
          resources:
              requests:
                cpu: 10m
                memory: 20Mi
              limits:
                cpu: 20m
                memory: 30Mi
      # imagePullSecrets:
      #   - name: dockercredentials
---
apiVersion: v1
kind: Service 
metadata:
  name: redis-service
  namespace: cache
spec:
  selector:
      app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer